#!/bin/sh
echo "Xft.dpi: 96
*dpi: 96
" > /home/user/.Xresources && xrandr --output eDP-1 --primary --mode 1920x1080 && cp ~/.config/polybar/config1080.ini ~/.config/polybar/config.ini && xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --mode 1920x1080 --pos 1920x0 --rotate normal;
