#!/bin/sh

if [ "$#" -lt 2 ]; then
   echo "Usage $0 [pass] [file]"
   exit
fi
for i in "${@:2}"; do
    calibredb --library-path=https://calibre.sermak.xyz --username=sermak --password="$1" add "$i"
done
