#!/bin/sh

a=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | tr ' ' '\n' | dmenu -p "Currently $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)")
if ! [ -z "$a" ]; then
   echo $a
   echo "$a" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi	