#!/bin/bash

file="/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference"
conservative="balance_power"

cpu=$(echo $(echo "scale=2;`cat /proc/cpuinfo | grep "^[c]pu MHz" | awk '{print $4}' | sort -n | sed -n '$p' | sed 's/\..*//'` / 1000" | bc -l) | sed 's/^\./0\./')
	if [[ "$(cat $file)" == "$conservative" ]]; then
	    echo "^c#00aa10^$cpu GHz^c#ddaaaa^$delim"
	else
	    echo "^c#aaaa10^$cpu GHz^c#ddaaaa^$delim"
	fi
