#!/usr/bin/env bash
if [[ $# -eq 3 ]]; then
    color1=$1
    color2=$2
    percentage=$(echo "scale=3; obase=16; $3" | bc)
else
    color1="#DD0010"
    color2="#00DD10"
    percentage=$(echo "scale=3; obase=16; $1" | bc)
fi

echo $percentage | grep "\." >/dev/null || percentage="$percentage.0"
test ${#percentage} -le 6 && percentage="${percentage}00000000000"

R1=${color1:1:2}
G1=${color1:3:2}
B1=${color1:5:2}

R2=${color2:1:2}
G2=${color2:3:2}
B2=${color2:5:2}


R=$(echo "scale=10; obase=16; ibase=16; ($R1*$percentage) + ($R2*(1-$percentage))" | bc | sed 's/\..*//')
G=$(echo "scale=10; obase=16; ibase=16; ($G1*$percentage) + ($G2*(1-$percentage))" | bc | sed 's/\..*//')
B=$(echo "scale=10; obase=16; ibase=16; ($B1*$percentage) + ($B2*(1-$percentage))" | bc | sed 's/\..*//')

test ${#R} -eq 1 && R=0$R
test ${#G} -eq 1 && G=0$G
test ${#B} -eq 1 && B=0$B

echo "#$R$G$B"

