#!/bin/bash
[[ $BLOCK_BUTTON = "1" ]] && st -e ~/.scripts/popwallpaper

apod title > ~/Pictures/wallpaperinfo
cat ~/Pictures/wallpaperinfo
echo >> ~/Pictures/wallpaperinfo
apod exp >> ~/Pictures/wallpaperinfo