#!/bin/bash
case $BLOCK_BUTTON in
    1) konsole --separate --hold -e sudo pacman -Syu && pacman -Qu | wc -l > ~/.pacupgrnum && pkill -RTMIN+8 i3blocks ;;
esac

pacman -Qu | wc -l | sed -e '/^0$/d' > ~/.pacupgrnum && pkill -RTMIN+8 i3blocks

cat ~/.pacupgrnum | sed -e "/^$/d"
