#!/bin/bash
# Dependencies are xclip and xorg-xprop.
# qrencode required for qrcode generation.
# groff/zathura required for man pages.
prim="$(xclip -o)"; [ -z "$prim" ] && exit

PID=$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)
PID=$(echo "$(pstree -lpA "$PID" | tail -n 1)" | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')
cd "$(readlink /proc/"$PID"/cwd)"
[ -f "$prim" ] && xdg-open "$prim" && exit
[ -d "$prim" ] && "$TERMINAL" "$prim" && exit

websearch() { "$BROWSER" "https://duckduckgo.com/?q=$@" ;}
wikipedia() { "$BROWSER" "https://en.wikipedia.org/wiki/$@" ;}
wiktionary() { "$BROWSER" "https://en.wiktionary.org/wiki/$@" ;}
maps() { "$BROWSER" "https://www.openstreetmap.org/search?query=$@" ;}
ebay() { "$BROWSER" "https://www.ebay.com/sch/$@" ;}

if [[ $prim =~ ^chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/ ]]; then
    prim=$(echo $prim | sed 's;chrome-extension\://oemmndcbldboiebfnladdacbdfmadadm/;;g')
fi
if [[ $prim =~ .*www.youtube.com/watch\?v=.* ]]; then
    choice=$(echo "music|mpv|video" | tr '|' '\n' | dmenu_color.sh "Play or Save as:") || exit 1

    if [ "$choice" = "music"  ]; then
	notify-send "Downloading $prim"
	youtube-dl -f bestaudio -o "$HOME/Documents/music/%(title)s.%(ext)s" $prim
    elif [ "$choice" = "video" ]; then
	notify-send "Downloading $prim"
	youtube-dl -o "$HOME/Documents/videos/%(title)s.%(ext)s" $prim
    elif [ "$choice" = "mpv" ]; then
	mpv --volume 60 $prim
    fi
    exit
elif [[ $prim =~ .*\.pdf$ ]]; then
    choice=$(echo "honors|bachelor|2|downloads" | tr '|' '\n' | dmenu_color.sh "Save in:") || exit 1

    if [ "$choice" = "honors"  ]; then
	notify-send "Saved $prim"
	cd "$HOME/nextcloud/honors"
	wget $prim
    elif [ "$choice" = "bachelor" ]; then
	notify-send "Saved $prim"
	cd "$HOME/nextcloud/bachelor"
	wget $prim
    elif [ "$choice" = "2" ]; then
	notify-send "Saved $prim"
	cd "$HOME/nextcloud/Uni/2"
	wget $prim
    elif [ "$choice" = "downloads" ]; then
	notify-send "Saved $prim"
	cd "$HOME/Downloads"
	wget $prim
    else
	notify-send "Saved $prim"
	cd $choice
	wget $prim
    fi
    exit
elif [[ $prim =~ "^.*\.[A-Za-z]\+.*" ]]; then
    choice=$(echo "music|video|meme|picture|download" | tr '|' '\n' | dmenu_color.sh "Save as:") || exit 1

    if [ "$choice" = "music"  ]; then
	notify-send "Downloading $prim"
	youtube-dl -f bestaudio -o "$HOME/Documents/music/%(title)s.%(ext)s" $prim
    elif [ "$choice" = "meme" ]; then
	cd "$HOME/nextcloud/(((memes)))/"
	notify-send "Saved $prim"
	wget $prim
    elif [ "$choice" = "video" ]; then
	notify-send "Downloading $prim"
	youtube-dl -o "$HOME/Documents/videos/%(title)s.%(ext)s" $prim
    elif [ "$choice" = "picture" ]; then
	echo d
    elif [ "$choice" = "download" ]; then
	echo e
    fi
    exit
fi
    
echo "$prim" | grep "^.*@.*\.[A-Za-z]\+$" >/dev/null && email() { xdg-email "$@" ;}
command -v qrencode >/dev/null && qrcode() { qrencode "$@" -s 10 -o /tmp/qr.png && xdg-open /tmp/qr.png ;}
man -k "^$prim$" >/dev/null && manual() { man -Tpdf "$prim" | zathura - ;}

func="$(declare -F | awk '{print $3}' | dmenu_color.sh "Plumb $prim to?")"

[ -z "$func" ] || "$func" "$prim"
